function [meanfmri_nii,rp_txt] = realignment(fmri_nii)

% SPM function call computes realignment params and updates headers
flags = struct( ...
	'quality',0.9, ...
	'sep',4, ...
	'fwhm',5, ...
	'rtm',1, ...
	'interp',2, ...
	'wrap',[0 0 0] ...
	);
spm_realign(func_file,flags);

% Filename of realignment params
[func_p,func_n,func_e] = fileparts(func_file);
rp_file = fullfile(func_p,['rp_' func_n '.txt']);

% Filenames for realigned images (we will return the not-resliced set)
rfunc_file = func_file;

% Now generate mean image via spm_reslice
flags = struct( ...
	'mask',true, ...
	'mean',true, ...
	'interp',4, ...
	'which',0, ...
	'wrap',[0 0 0], ...
	'prefix','r' ...
	);
spm_reslice(func_file,flags);
meanfunc_file = fullfile(func_p,['mean' func_n func_e]);
