% Test script to verify that the matlab code is working ahead of
% compilation.
%
% SPM12 needs to be in the matlab path.
%
% We also need some test data in the ../INPUTS directory, and the
% ../OUTPUTS directory must exist. Take a look at the ../.gitignore file,
% which is set up so that these test data are excluded from the git
% repository.

example_main( ...
	't1_niigz','../INPUTS/t1.nii.gz', ...
	'fmri_niigz','../INPUTS/fmri.nii.gz', ...
	'fwhm','6', ...
	'out_dir','../OUTPUTS', ...
	'xnat_project','TEST_PROJ', ...
	'xnat_subject','TEST_SUBJ', ...
	'xnat_session','TEST_SESS', ...
	'xnat_scan_t1','TEST_SCAN_T1', ...
	'xnat_scan_fmri','TEST_SCAN_FMRI' ...
	);

