function [meanfmri_niigz,rfmri_niigz,srfmri_niigz] = zip_outputs( ...
	out_dir,meanfmri_nii,rfmri_nii,srfmri_nii)

% Zip images
system([ ...
	'cd ' out_dir ' && gzip -f ' ...
	'filtered_keepgm_noscrub.nii ' ...
	'filtered_keepgm_scrub.nii ' ...
	'filtered_removegm_noscrub.nii ' ...
	'filtered_removegm_scrub.nii ' ...
	'wmeanadfunc.nii ' ...
	'wadfunc.nii ' ...
	'rwroi_labels.nii ' ...
	'roi_snr.nii ' ...
	]);

if params.output_maps
	system([ ...
	'cd ' out_dir ' && gzip -f ' ...
	'Zmap_keepgm_noscrub.nii ' ...
	'Zmap_keepgm_scrub.nii ' ...
	'Zmap_removegm_noscrub.nii ' ...
	'Zmap_removegm_scrub.nii ' ...
	'sZmap_keepgm_noscrub.nii ' ...
	'sZmap_keepgm_scrub.nii ' ...
	'sZmap_removegm_noscrub.nii ' ...
	'sZmap_removegm_scrub.nii ' ...
	]);
end

% Clean up intermediate files
delete([out_dir '/*.png']);
delete([out_dir '/*.nii']);
delete([out_dir '/coregmat.txt']);
